repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Go formatting and linting
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy

  # Node.js/Frontend linting (local)
  - repo: local
    hooks:
      - id: eslint-frontend
        name: ESLint (Frontend)
        entry: bash -c 'cd frontend && npm run lint'
        language: system
        files: ^frontend/.*\.(ts|tsx|js|jsx)$
        pass_filenames: false

  # Solidity formatting (Foundry)
  - repo: local
    hooks:
      - id: forge-fmt
        name: Forge Format
        entry: bash -c 'cd contracts && forge fmt --check'
        language: system
        files: ^contracts/.*\.sol$
        pass_filenames: false

  # Secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

  # AI Usage compliance check
  - repo: local
    hooks:
      - id: require-ai-usage
        name: Require AI_USAGE.md when code changes
        entry: bash scripts/require_ai_usage_simple.sh
        language: system
        stages: [commit]
      - id: require-ai-usage-windows
        name: Require AI_USAGE.md when code changes (Windows)
        entry: powershell -ExecutionPolicy Bypass -File scripts/require_ai_usage_simple.ps1
        language: system
        stages: [commit]
